import { config } from "../../../config";
import { IWgClientsDto } from "../wgclient";
import { IWgServerDto } from "../wgserver";

const { WG_PORT, WG_PRE_UP, WG_POST_UP, WG_PRE_DOWN, WG_POST_DOWN } = config;

export const getWireguardSeverBlockConfig = (server: IWgServerDto) => {
  return `
# Note: Do not edit this file directly.
# Your changes will be overwritten!

# Server
[Interface]
PrivateKey = ${server.privateKey}
Address = ${server.address}/24
ListenPort = ${WG_PORT}
PreUp = ${WG_PRE_UP}
PreDown = ${WG_PRE_DOWN}
PostUp = ${WG_POST_UP}
PostDown = ${WG_POST_DOWN}
`;
};

export const getWireguardPeersConfig = (client: IWgClientsDto) => {
  return `

# Client: ${client.name} (${client.id})
[Peer]
PublicKey = ${client.publicKey}
PresharedKey = ${client.preSharedKey}
AllowedIPs = ${client.address}/32`;
};
